### ISSUE TITLE
wifi.tpl fails after recent pull

### ISSUE THREAD

**Issue by morganrallen** [Spritetm/libesphttpd#10]
I'd been working with f57690ab7b866cd070b174d3c321010a15816cc0 but since pulling in the most recent changes wifi.tpl no longer renders. Of note index.tpl renders fine and increments the counter in the template as expected.

Picking apart `tplWlan` I see the 4 expected template tokens getting processes, and the function is hit a 5th time returning `HTTPD_CGI_DONE`.

The result I get is the template rendered right up until `%currSsid%`

```
...
<script type="text/javascript">

var xhr=j();
var currAp="
```

And the connection closes there.

**Comment by morganrallen** [comment]
Tracking the issue down a bit now, this makes it work.

```
  } else if (strcmp(token, "currSsid")==0 && strlen((char*)stconf.ssid)>0) {
    strcpy(buff, (char*)stconf.ssid);
  } else if (strcmp(token, "WiFiPasswd")==0 && strlen((char*)stconf.password)>0) {
    strcpy(buff, (char*)stconf.password);
```

So maybe writing the empty `buff` to `connData` is causing the problem...

**Comment by Spritetm** [comment]
It seems indeed that my new chunking code doesn't like zero-length buffers very much. I need to overhaul it anyway, my current implementation is needlessly inefficient.

**Comment by Spritetm** [comment]
Can you try a38909a ? That should fix this bug as well.

**Comment by morganrallen** [comment]
Nice one, looks good.

**Comment by Spritetm** [comment]
Cool, then I assume this is fixed :)
