### ISSUE TITLE
Aiee, conn pool overflow!

### ISSUE THREAD

**Issue by valkuc** [Spritetm/libesphttpd#19]
I can't figure out why and exactly when this happens, but it looks like some times connection not getting closed/free and after some period of time connection pool gets overflowed. I'm using SDK 1.5.4 and the code snapshot from revision https://github.com/Spritetm/libesphttpd/tree/c1d3c14e6e56ca6c860485324feafa866648d2ea

I will investigate more on this issue and will try to figure out why this happens.

**Comment by valkuc** [comment]
Okay, I found simple way to reproduce this. Just target your browser to ESP and hold F5 for few seconds (until browser start to refuse loading page). After that connection pool will get full and will never be cleared for new connections until reboot. Huh... DOS atack test failed :)

What is written above is a just quick steps to reproduce my situation, actually same occurs with normal application usage but needs more time.

**Comment by Spritetm** [comment]
\o/
