### ISSUE TITLE
The percentage symbol (%) is not correctly interpreted in HTML documents

### ISSUE THREAD

**Issue by mroavi** [Spritetm/libesphttpd#23]
**Fragment of original HTML file:**
`#center {
    padding: 10px 20px;
    width: 100%;
}
`

**Response from the server:**
`#center {
    padding: 10px 20px;
    width: 100
'#  ;
}`

The consequence is that the whole webpage is incorrectly displayed.

**Comment by valkuc** [comment]
You probably using template processing CGI routine (cgiEspFsTemplate). In this case you must "escape" percent symbol - write %%

**Comment by mroavi** [comment]
That worked. Thanks.
