### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by UncleRus** [Spritetm/libesphttpd#33]
Under what license this project is? Is it GPL2, GPL3, MIT, BSD2, BSD3 or proprietary?

**Comment by Spritetm** [comment]
As it says at the top of nearly every C file:
/*
- ----------------------------------------------------------------------------
- "THE BEER-WARE LICENSE" (Revision 42):
- Jeroen Domburg jeroen@spritesmods.com wrote this file. As long as you retain 
- this notice you can do whatever you want with this stuff. If we meet some day, 
- and you think this stuff is worth it, you can buy me a beer in return. 
- ----------------------------------------------------------------------------
  */

**Comment by UncleRus** [comment]
Whoops, my bad. :)
