### ISSUE TITLE
need help: espFsInit failed where flashAddress not aligned to 4 bytes

### ISSUE THREAD

**Issue by ustccw** [Spritetm/libesphttpd#48]
Hi,
when tried to adapt your excellent esphttpd code to [ESP8266_IOT_PLATFORM](https://github.com/espressif/ESP8266_IOT_PLATFORM)
the error happened like the following:
https://github.com/Spritetm/libesphttpd/blob/b7bb4a625bf4a2c7e7eb699caa244ca7989fd079/espfs/espfs.c#L83
even if i comment the flashAddress align check, the error still happened at the other place. 
could you help me to make it work?

Best regards
CW

**Comment by Spritetm** [comment]
That means, well that the filesystem isn't aligned properly. How do you compile this all?

(Also, you do know I'm one of your colleagues, right? I'm Jeroen, feel free to walk to my desk or mail me on my Espressif mail address if you want more direct help.)

**Comment by ustccw** [comment]
many thanks to you big help! it works now!  (ps:  i know there was a `Jeroen` in company legend long ago, and did not know it is you, haha, it is my honor to be your colleague.)
